M48
; DRILL file {KiCad 8.0.4} date 2024-08-11T22:53:45+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-11T22:53:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X137.29Y-174.35
X143.07Y-174.35
T2
X130.0Y-153.8
X140.0Y-122.6
X150.3Y-153.8
M30
