M48
; DRILL file {KiCad 8.0.8} date 2025-04-09T13:22:35+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-09T13:22:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X137.29Y-174.35
X143.07Y-174.35
T2
X130.0Y-153.8
X140.0Y-122.6
X150.3Y-153.8
M30
